### ISSUE TITLE
动画插值器无法设置

### ISSUE THREAD

**Issue by zhangzhiao** [xiangang/RecyclerViewLoopScrollAnimation#1]
` var scrollAnimatorInterpolator = AccelerateDecelerateInterpolator()`
因为内部使用的是AccelerateDecelerateInterpolator，并且没有声明变量的类型为BaseInterpolator，所以插值器是无法更改的

**Comment by xiangang** [comment]
感谢反馈，已修复[1343b56](https://github.com/ossrs/srs/commit/c6eddc72e9a095d7e38a24673b0e023eb3c73ddd)
